object fmSelectParser: TfmSelectParser
  Left = 0
  Top = 0
  BorderStyle = bsDialog
  Caption = 'Select Parser'
  ClientHeight = 415
  ClientWidth = 561
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poOwnerFormCenter
  PixelsPerInch = 96
  TextHeight = 13
  object laDescription: TLabel
    Left = 32
    Top = 80
    Width = 454
    Height = 13
    Caption = 
      'Parser is the code that opens and parses (analizes) the TLM file' +
      's. TLM Viewer has two parsers.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsItalic]
    ParentFont = False
  end
  object laSelectCaption: TLabel
    Left = 32
    Top = 99
    Width = 208
    Height = 13
    Caption = 'Select parser to open the selected TLM file:'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsItalic]
    ParentFont = False
  end
  object laNewDescription: TLabel
    Left = 96
    Top = 159
    Width = 419
    Height = 26
    AutoSize = False
    Caption = 
      'The New Parser is the recommended one and should be used in most' +
      ' cases. It supports all latest firmwares as well as iX12 RTC.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsItalic]
    ParentFont = False
    WordWrap = True
  end
  object laOldDescription: TLabel
    Left = 96
    Top = 223
    Width = 418
    Height = 42
    AutoSize = False
    Caption = 
      'The Old Parser is the initial parsed used by the TLM Viewer. It ' +
      'can read TLM files generated by old Spektrum firmware as well as' +
      ' corrupted TLM files. Use this parser only in case when the New ' +
      'Parser does not work (can not read TLM file correctly).'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsItalic]
    ParentFont = False
    WordWrap = True
  end
  object laDoNotAskDescription: TLabel
    Left = 56
    Top = 319
    Width = 479
    Height = 13
    Caption = 
      'If you check this the selected Parser will be used as default on' +
      'e. You can change it later in Settings.'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsItalic]
    ParentFont = False
  end
  object beBottom: TBevel
    Left = 16
    Top = 352
    Width = 537
    Height = 10
    Shape = bsBottomLine
  end
  object paTop: TPanel
    Left = 0
    Top = 0
    Width = 561
    Height = 65
    Align = alTop
    BevelOuter = bvNone
    Color = clWhite
    ParentBackground = False
    TabOrder = 0
    object laTitle: TLabel
      Left = 16
      Top = 14
      Width = 498
      Height = 13
      Caption = 
        'This dialog allows you to select parsed that should be used to o' +
        'pen the selected TLM file.'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold]
      ParentFont = False
    end
    object laHow: TLabel
      Left = 32
      Top = 40
      Width = 174
      Height = 13
      Caption = 'How would you like to open the file: '
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsItalic]
      ParentFont = False
    end
    object laFileName: TLabel
      Left = 212
      Top = 40
      Width = 74
      Height = 13
      Caption = 'TLMFileName'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Tahoma'
      Font.Style = [fsBold, fsItalic]
      ParentFont = False
    end
  end
  object rbNew: TRadioButton
    Left = 80
    Top = 136
    Width = 193
    Height = 17
    Caption = 'New parser (recommended)'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 1
  end
  object rbOld: TRadioButton
    Left = 80
    Top = 200
    Width = 209
    Height = 17
    Caption = 'Old parser (for legacy TLM files)'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 2
  end
  object cbDoNotAsk: TCheckBox
    Left = 40
    Top = 296
    Width = 129
    Height = 17
    Caption = 'Do not ask again'
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    TabOrder = 3
  end
  object btOpen: TButton
    Left = 379
    Top = 376
    Width = 75
    Height = 25
    Caption = 'Open'
    Default = True
    ModalResult = 1
    TabOrder = 4
  end
  object btCancel: TButton
    Left = 460
    Top = 376
    Width = 75
    Height = 25
    Cancel = True
    Caption = 'Cancel'
    ModalResult = 2
    TabOrder = 5
  end
end
